### ISSUE TITLE
Trelliscope in POSIT Connect

### ISSUE THREAD

**Issue by dcmg21** [trelliscope/trelliscope#9]
Are there any instructions on running trelliscope in Shiny on Posit Connect?  I was able to run this package find locally but unable to have it render in posit connect.  More examples of different basic shiny apps would be helpful.  That being said, I love this package!

Thanks,
Drew

**Comment by hafen** [comment]
Please see here: https://trelliscope.org/trelliscope/articles/embed.html

If you run into any issues or have any suggestions, let me know. Thanks!

**Comment by joannalingzj** [comment]
Hello! I've also run into problems running trelliscope in Shiny on Posit Connect. Running locally also works fine for me. 

What happens is that the htmlwidget does not load. I've uploaded a screenshot of the mars rover example from the tutorial as an example. 

![Capture](https://github.com/trelliscope/trelliscope/assets/48317523/300a1ce6-9de0-490c-b8b9-792e49274b83)

This comes with the messages below and no error messages. 
01/09 03:55:20.241 (GMT)
ℹ Trelliscope written to
01/09 03:55:20.241 (GMT)
/opt/rstudio-connect/mnt/tmp/Rtmpz2cTkQ/file13540438a1f4f/test/index.html
01/09 03:55:20.241 (GMT)
Open this file or call view_trelliscope() to view.

Another example has one error message but this only appears once when publishing and then does not appear anymore. 
01/09 03:15:52.462 (GMT)
ℹ Trelliscope written to
01/09 03:15:52.463 (GMT)
/opt/rstudio-connect/mnt/tmp/RtmpcXGzKK/file9ab26dc99ecc/index.html Open this
01/09 03:15:52.463 (GMT)
file or call view_trelliscope() to view.
01/09 03:15:52.463 (GMT)
Cannot visit /opt/rstudio-connect/mnt/tmp/RtmpcXGzKK/file9ab26dc99ecc/index.html because the browseURL function is disabled.

Thanks! 
Joanna

**Comment by hafen** [comment]
Thanks for the report. What version of trelliscope are you using?

**Comment by joannalingzj** [comment]
I'm using trelliscope_0.1.6
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

**Comment by hafen** [comment]
If you can install the latest version, I think I have fixed it. There were a few issues. One was a small tweak in the iframe path that the app uses, which is internal so you don't need to worry about that. The other is that it appears that Posit Connect and shinyapps.io don't like jsonp files, which Trelliscope creates by default, so you need to add `jsonp = FALSE` in `as_trelliscope_df()`. Docs have been updated [here](https://trelliscope.org/trelliscope/articles/embed.html#embedding-trelliscope-in-shiny).

**Comment by joannalingzj** [comment]
Thanks! That works now. You're amazing! Really love the package.
